# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-24 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=140)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=140)),
                ('experience', models.CharField(max_length=140)),
                ('equipment', models.CharField(max_length=140)),
            ],
        ),
    ]
