# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newworkouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_workout',
            name='reps',
            field=models.CharField(default='yas trick', max_length=140),
            preserve_default=False,
        ),
    ]
