# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-21 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newworkouts', '0002_post_workout_reps'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rep_Configurations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('purpose', models.CharField(max_length=140)),
                ('reps', models.CharField(max_length=140)),
            ],
        ),
    ]
