# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-21 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newworkouts', '0003_rep_configurations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rep_configurations',
            old_name='title',
            new_name='configuration',
        ),
        migrations.AddField(
            model_name='rep_configurations',
            name='difficulty',
            field=models.CharField(default='blah', max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rep_configurations',
            name='sets',
            field=models.CharField(default='a', max_length=140),
            preserve_default=False,
        ),
    ]
