# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-22 01:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newworkouts', '0004_auto_20170721_1224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post_workout',
            old_name='reps',
            new_name='purpose',
        ),
        migrations.RenameField(
            model_name='rep_configurations',
            old_name='reps',
            new_name='extreme_sets',
        ),
        migrations.RemoveField(
            model_name='rep_configurations',
            name='configuration',
        ),
        migrations.RemoveField(
            model_name='rep_configurations',
            name='sets',
        ),
        migrations.AddField(
            model_name='rep_configurations',
            name='easy_reps',
            field=models.CharField(default='fuck', max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rep_configurations',
            name='easy_sets',
            field=models.CharField(default='fuck', max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rep_configurations',
            name='easy_timer',
            field=models.CharField(default='fuck', max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rep_configurations',
            name='extreme_reps',
            field=models.CharField(default='fuck', max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rep_configurations',
            name='extreme_timer',
            field=models.CharField(default='fuck', max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rep_configurations',
            name='hard_reps',
            field=models.CharField(default='fuck', max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rep_configurations',
            name='hard_sets',
            field=models.CharField(default='fuck', max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rep_configurations',
            name='hard_timer',
            field=models.CharField(default='fuck', max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rep_configurations',
            name='intermediate_reps',
            field=models.CharField(default='fuck', max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rep_configurations',
            name='intermediate_sets',
            field=models.CharField(default='fuck', max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rep_configurations',
            name='intermediate_timer',
            field=models.CharField(default='fuck', max_length=140),
            preserve_default=False,
        ),
    ]
