# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-22 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newworkouts', '0006_auto_20170721_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time_Configurations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('easy_timer', models.CharField(max_length=140)),
                ('intermediate_timer', models.CharField(max_length=140)),
                ('hard_timer', models.CharField(max_length=140)),
                ('extreme_timer', models.CharField(max_length=140)),
            ],
        ),
        migrations.RemoveField(
            model_name='rep_configurations',
            name='easy_timer',
        ),
        migrations.RemoveField(
            model_name='rep_configurations',
            name='extreme_timer',
        ),
        migrations.RemoveField(
            model_name='rep_configurations',
            name='hard_timer',
        ),
        migrations.RemoveField(
            model_name='rep_configurations',
            name='intermediate_timer',
        ),
    ]
